src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Article
{
    const STATUS_NEW = 'new';
    const STATUS_IN_PROGRESS = 'in_progress';
    const STATUS_REVIEW_DONE = 'review_done';
    const STATUS_REPAIR = 'repair';
    const STATUS_REPAIR_DONE = 'repair_done';
    const STATUS_ARCHIVED = 'archived';

    const STATUS_DONE = 'done';
    const STATUS_DECLINE = 'decline';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $authors_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status = self::STATUS_NEW;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleFile", mappedBy="article", orphanRemoval=true)
     */
    private $articleFiles;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ArticleTheme", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $theme;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"merge"}, inversedBy="article")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="article", orphanRemoval=true)
     */
    private $reviews;

    public $file;

    public function __construct()
    {
        $this->articleFiles = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthorsName(): ?string
    {
        return $this->authors_name;
    }

    public function setAuthorsName(string $authors_name): self
    {
        $this->authors_name = $authors_name;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    /**
     * @return Collection|ArticleFile[]
     */
    public function getArticleFiles(): Collection
    {
        return $this->articleFiles;
    }

    public function addArticleFile(ArticleFile $articleFile): self
    {
        if (!$this->articleFiles->contains($articleFile)) {
            $this->articleFiles[] = $articleFile;
            $articleFile->setArticle($this);
        }

        return $this;
    }

    public function removeArticleFile(ArticleFile $articleFile): self
    {
        if ($this->articleFiles->contains($articleFile)) {
            $this->articleFiles->removeElement($articleFile);
            // set the owning side to null (unless already changed)
            if ($articleFile->getArticle() === $this) {
                $articleFile->setArticle(null);
            }
        }

        return $this;
    }

    public function getTheme(): ?ArticleTheme
    {
        return $this->theme;
    }

    public function getThemeName(): ?string
    {
        return $this->getTheme()->getName();
    }

    public function setTheme(?ArticleTheme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->setCreatedDate(new \DateTime());
    }


    public function getActualStatus()
    {
        switch ($this->getStatus()) {
            case self::STATUS_NEW:
                return 'nový';
                break;
            case self::STATUS_IN_PROGRESS:
                return 'čeká se na recenzi';
                break;
            case self::STATUS_REVIEW_DONE:
                return 'recenze hotová';
                break;
            case self::STATUS_REPAIR:
                return 'požadavek na úpravu';
                break;
            case self::STATUS_DONE:
                return 'Schválen';
                break;
            case self::STATUS_DECLINE:
                return 'Zamítnut';
                break;

        }
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setArticle($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getArticle() === $this) {
                $review->setArticle(null);
            }
        }

        return $this;
    }
}

templates/index/about_us.twig
{% extends 'base.twig' %}
{% block body %}
    <div class="content">
        <div class="row">
            <div class="col-3">
                {% include '_include/menu.twig' %}
            </div>
              <div class="col-9">
                <h1>O nás</h1>
                <div><p>Adresa nakladatele: Vysoká škola polytechnická Jihlava, redakce LOGOS POLYTECHNIKOS, Tolstého 1556/16, 586 01 Jihlava</p></div>
                <div><h1>Náš tým</h1>
                        <div>Šéfredaktor</div>
                        <p>doc. Ing. Zdeněk Horák, Ph.D. (Vysoká škola polytechnická Jihlava)</p>
                        <br>
                        <div>Redakční rada</div>
                        <p>prof. PhDr. RNDr. Martin Boltižiar, PhD. (Univerzita Konštantína Filozofa v Nitre)<br>
                          prof. RNDr. Helena Brožová, CSc. (Česká zemědělská univerzita v Praze)<br>
                          doc. PhDr. Lada Cetlová, PhD. (Vysoká škola polytechnická Jihlava)<br>
                          prof. Mgr. Ing. Martin Dlouhý, Dr. MSc. (Vysoká škola ekonomická v Praze)<br>
                          prof. Ing. Tomáš Dostál, DrSc. (Vysoká škola polytechnická Jihlava)<br>
                          doc. Ing. Jiří Dušek, Ph.D. (Vysoká škola evropských a regionálních studií)<br>
                          doc. RNDr. Petr Gurka, CSc. (Vysoká škola polytechnická Jihlava)<br>
                          Ing. Veronika Hedija, Ph.D. (Vysoká škola polytechnická Jihlava)<br>
                          doc. Ing. Zdeněk Horák, Ph.D. (Vysoká škola polytechnická Jihlava)<br>
                          Ing. Ivica Linderová, PhD. (Vysoká škola polytechnická Jihlava)<br>
                          prof. MUDr. Aleš Roztočil, CSc. (Vysoká škola polytechnická Jihlava)<br>
                          doc. PhDr. David Urban, Ph.D. (Vysoká škola polytechnická Jihlava)<br>
                          doc. Dr. Ing. Jan Voráček, CSc. (Vysoká škola polytechnická Jihlava)<br>
                          RNDr. PaedDr. Ján Veselovský, PhD. (Univerzita Konštantína Filozofa v Nitre)<br>
                          doc. Ing. Libor Žídek, Ph.D. (Masarykova univerzita Brno)</p>
                </div>

                <div><p>Pro více informací se prosím obraťe na kontaktní osobu. <br>
                        Kontaktní osoba: Bc. Zuzana Mafková:   <a href="mailto:zuzana.mafkova@vspj.cz">zuzana.mafkova@vspj.cz</a></p>
                </div>
                <br><br>
            </div>
        </div>

    </div>


{% endblock %}

templates/index/author.twig
{% extends 'base.twig' %}
{% block body %}
    <div class="content">
        <div class="row">
            <div class="col-3">
                {% include '/_include/menu.twig' %}
            </div>
            <div class="col-9">

                {% if user is defined and user %}
                    <h1>Moje Články</h1>
                    {% if articles %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Stav</th>
                                <th scope="col">Téma článku</th>
                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in articles %}
                                <tr>

                                    <th scope="row">{{ a.id }}</th>
                                    <td>{{ a.getName() }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>
                                    <td>
                                        <strong>{{ a.getActualStatus() }}</strong>
                                        {% if a.getStatus() =='review_done' %}
                                            <a class="btn btn-outline-info" href="/author-recenze/{{ a.getId() }}">Zobrazit recenze</a>
                                        {% endif %}
                                        {% if a.getStatus() =='repair' %}
                                            <a class="btn btn-outline-info" href="/author-recenze/{{ a.getId() }}">Zobrazit recenze</a>
                                            <a class="btn btn-outline-info" href="/clanek/{{ a.getId() }}">Upravit článek</a>
                                        {% endif %}
                                    </td>

                                    <td>{{ a.getThemeName() }}</td>
                                    <td>{{ a.createdDate.format('d.m.Y') }}</td>
                                    <td><a class="btn btn-success" href="/article-files/{{ a.getId() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>Nejsou tu žádné články</p>

                    {% endif %}


                {% endif %}


            </div>
        </div>

    </div>
{% endblock %}

templates/index/autor.twig
{% extends 'base.twig' %}
{% block body %}
    <div class="content">
        <div class="row">
            <div class="col-3">
                {% include '/_include/menu.twig' %}
            </div>
            <div class="col-9">

                {% if user is defined and user %}


                    <h1>Moje Články</h1>


                    {% if articles %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Stav</th>
                                <th scope="col">Téma článku</th>
                                <th scope="col">Komentář</th>
                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                                {#
                                    <th scope="col">Akce</th>
                                #}

                            </tr>
                            </thead>
                            <tbody>
                            {% for a in articles %}
                                <tr>
                                    <th scope="row">{{ a.id }}</th>
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.autorsName }}</td>
                                    <td><strong>{{ a.getActualStatus() }}</strong></td>
                                    <td>{{ a.theme }}</td>
                                    <td>{{ a.comment }}</td>
                                    <td>{{ a.createdDate.format('Y-m-d H:i:s') }}</td>
                                    <td><a class="btn btn-success" href="/article-files/{{ a.getId() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                    {% if a.status=='repair' %}
                                        <td>

                                            <a href="/recenze/{{ a.getId() }}"
                                               class="btn btn-block btn-outline-primary">Recenze</a>
                                            <a href="/clanek/{{ a.getId() }}" class="btn btn-block btn-outline-danger">Upravit</a>

                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>Nejsou tu žádné články</p>

                    {% endif %}


                {% endif %}


            </div>
        </div>

    </div>
{% endblock %}

templates/index/contact.twig
{% extends 'base.twig' %}
{% block body %}
    <div class="content">
        <div class="row">
            <div class="col-3">
                {% include '_include/menu.twig' %}
            </div>
            <div class="col-9">
                <h1>Máte nějaké dotazy ?</h1>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/index/index.twig
{% extends 'base.twig' %}
{% block body %}
    <div class="content">
        <div class="row">
            <div class="col-3">
                {% include '_include/menu.twig' %}
            </div>
            <div class="col-9">
                <h1>Informace</h1>
                <div><p style="margin-left: 40px;"><b>LOGOS POLYTECHNIKOS je vysokoškolský odborný recenzovaný
                            časopis</b><br>,
                        který slouží pro publikační aktivity akademických pracovníků Vysoké školy polytechnické
                        Jihlava i jiných vysokých škol,<br>
                        univerzit a výzkumných organizací. Je veden na seznamu recenzovaných odborných a vědeckých
                        časopisů <b>ERIH PLUS</b> - European<br>
                        Reference Index for the Humanities and the Social Sciences
                        (<a target="_blank"
                            href="https://dbh.nsd.uib.no/publiseringskanaler/erihplus/periodical/info?id=488187">https://dbh.nsd.uib.no/publiseringskanaler/erihplus/periodical/info?id=488187</a>).
                    </p></div>
                <div><p style="margin-left: 40px;">Od roku 2010 do roku 2018 byl časopis vydáván čtyřikrát ročně v
                        elektronické a tištěné podobě. Od roku 2019 vychází třikrát <br>
                        ročně v elektronické verzi. Redakční rada časopisu sestává z interních i externích
                        odborníků. Funkci šéfredaktora zastává prorektor <br>
                        pro tvůrčí a projektovou činnost Vysoké školy polytechnické Jihlava. Funkce odpovědných
                        redaktorů jednotlivých čísel přísluší <br>
                        vedoucím kateder Vysoké školy polytechnické Jihlava. Veškeré vydávané příspěvky prochází
                        recenzním řízením a jsou pečlivě <br>
                        redigovány.</p></div>
                <div><p style="margin-left: 40px;"><b>Tematické a obsahové zaměření časopisu</b> reflektuje potřeby
                        oborových kateder Vysoké školy polytechnické Jihlava.<br>
                        Na základě souhlasu odpovědného redaktora mohou katedry poskytnout publikační prostor i
                        odborníkům bez zaměstnanecké vazby k Vysoké <br>
                        škole polytechnické Jihlava.</p></div>
                <div><p style="margin-left: 40px;"><b>V časopise je možné publikovat</b> odborné články, statě,
                        přehledové studie, recenze a další typy odborných příspěvků <br>
                        v českém, slovenském a anglickém jazyce. Do recenzního řízení jsou přijímány příspěvky
                        tematicky odpovídající zaměření <br>
                        časopisu a formálně upravené dle redakční šablony.</p></div>
                <br><br>
            </div>
        </div>

    </div>
{% endblock %}

templates/index/login.twig
{% extends 'base.twig' %}



{% block body %}

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="row" style="text-align: center">
                <div class="col-12" style="margin-top:120px">
                    {{ form_start(form) }}

                    {{ form_widget(form) }}

                    {{ form_end(form) }}
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12" style="text-align: center;border: #959595 solid 3px">
                    <h3>Autoři</h3>
                    {% for u in authors %}
                        {{ u.email }} / {{ u.password }}
                    {% endfor %}
                    <h3>Redaktoři</h3>
                    {% for u in redactors %}
                        {{ u.email }} / {{ u.password }}
                    {% endfor %}
                    <h3>Recenzenti</h3>
                    {% for u in recenzents %}
                        {{ u.email }} / {{ u.password }}<br/>
                    {% endfor %}

                </div>
            </div>
        </div>
        <div class="col-4"></div>
    </div>



{% endblock %}

templates/index/redactor.twig
{% extends 'base.twig' %}
{% block body %}
    <div class="content">
        <div class="row">
            <div class="col-3">
                {% include '_include/menu.twig' %}
            </div>
            <div class="col-9">

                {% if user is defined and user %}

                    <h1 class="text-center">Články</h1>

                    <h3>Nové</h3>
                    {% if newArticles %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Téma článku</th>

                                <th scope="col">Soubory</th>
                                <th scope="col">Recenzenti</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in newArticles %}
                                <tr>
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>
                                    <td>{{ a.getThemeName() }}</td>

                                    <td><a class="btn btn-success" href="/article-files/{{ a.getId() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                    <td>
                                        {% set form = formObject.createView %}
                                        {{ form_start(form,{'attr': {'id': a.id() }}) }}
                                        {{ form_widget(form.id_article,{'value':a.id}) }}
                                        {{ form_widget(form.users) }}
                                        {{ form_end(form) }}
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <small>Nejsou tu žádné články</small>

                    {% endif %}

                    <hr>
                    <h3>Čekající na rezenzi</h3>
                    {% if waitingArticles %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Téma článku</th>
                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in waitingArticles %}
                                <tr class="mt-5">
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>
                                    <td>{{ a.getThemeName() }}</td>
                                    <td>{{ a.createdDate.format('Y-m-d H:i:s') }}</td>
                                    <td><a class="btn btn-outline-success" href="/article-files/{{ a.getID() }}"><i
                                                    class="fa fa-eye"></i></a></td>


                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <small>Nejsou tu žádné články</small>

                    {% endif %}

                    <hr>
                    <h3>Hotové recenze</h3>
                    {% if reviewDone %}

                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Téma článku</th>

                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                                <th scope="col">Akce</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in reviewDone %}
                                <tr class="mt-5">
                                    <th>{{ a.id }}</th>
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>

                                    <td>{{ a.getThemeName }}</td>

                                    <td>{{ a.createdDate.format('Y-m-d H:i:s') }}</td>
                                    <td><a class="btn btn-success" href="/article-files/{{ a.getID() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                    <td>
                                        <a class="btn btn-block btn-outline-info" href="/clanek/{{ a.getID() }}">
                                            Upravit
                                        </a>
                                        <a class="btn btn-block btn-outline-success"
                                           href="/admin-recenze/{{ a.getID() }}">
                                            Zobrazit recenze
                                        </a>

                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <small>Nejsou tu žádné články</small>
                    {% endif %}

                    <hr>
                    <h3>Čekají na opravu</h3>
                    {% if toRepair %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Téma článku</th>

                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                                <th scope="col">Akce</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in toRepair %}
                                <tr class="mt-5">
                                    <th>{{ a.id }}</th>
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>

                                    <td>{{ a.getThemeName }}</td>

                                    <td>{{ a.createdDate.format('Y-m-d H:i:s') }}</td>
                                    <td><a class="btn btn-success" href="/article-files/{{ a.getID() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                    <td>
                                        <a class="btn btn-block btn-outline-info" href="/clanek/{{ a.getID() }}">
                                            Upravit
                                        </a>
                                        <a class="btn btn-block btn-outline-success"
                                           href="/admin-recenze/{{ a.getID() }}">
                                            Zobrazit recenze
                                        </a>

                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <small>Nejsou tu žádné články</small>
                    {% endif %}

                    <hr>
                    <h3>Opravené</h3>
                    {% if repaired %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Téma článku</th>

                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                                <th scope="col">Akce</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in repaired %}
                                <tr class="mt-5">
                                    <th>{{ a.id }}</th>
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>

                                    <td>{{ a.getThemeName }}</td>

                                    <td>{{ a.createdDate.format('Y-m-d H:i:s') }}</td>
                                    <td><a class="btn btn-success" href="/article-files/{{ a.getID() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                    <td>
                                        <a class="btn btn-block btn-outline-info" href="/clanek/{{ a.getID() }}">
                                            Upravit
                                        </a>
                                        <a class="btn btn-block btn-outline-success"
                                           href="/admin-recenze/{{ a.getID() }}">
                                            Zobrazit recenze
                                        </a>

                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <small>Nejsou tu žádné články</small>

                    {% endif %}
                    <hr>
                    <h3>Dokončené</h3>
                    {% if endArticles %}
                        <table class="table table-striped text-center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Název</th>
                                <th scope="col">Autorský tým</th>
                                <th scope="col">Téma článku</th>

                                <th scope="col">Vytvořeno</th>
                                <th scope="col">Soubory</th>
                                <th scope="col">Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for a in endArticles %}
                                <tr class="mt-5">
                                    <th>{{ a.id }}</th>
                                    <td>{{ a.name }}</td>
                                    <td>{{ a.getAuthorsName() }}</td>

                                    <td>{{ a.getThemeName }}</td>

                                    <td>{{ a.createdDate.format('Y-m-d H:i:s') }}</td>
                                    <td><a class="btn btn-success" href="/article-files/{{ a.getID() }}"><i
                                                    class="fa fa-eye"></i></a></td>
                                    <td>{{ a.getActualStatus() }}
                                        <a class="btn btn-outline-info" href="/archive/{{ a.getId() }}">Archivovat</a>
                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <small>Nejsou tu žádné články</small>

                    {% endif %}

                {% endif %}


            </div>
        </div>

    </div>
{% endblock %}